### ISSUE TITLE
Duplicate BUSCOs

### ISSUE THREAD

**Issue by paul-bio** [Gaius-Augustus/BRAKER#734]
Hello.
I recently used Braker3 (RNA + protein), which generates more BUSCO values than Maker3.

However, I have one question to be answered.
There are too many duplicated BUSCOs.

This is the code I used to run braker3.
![image](https://github.com/Gaius-Augustus/BRAKER/assets/73869977/2892b13a-5c22-4379-aafc-8457a2d1d27b)

my result
![image](https://github.com/Gaius-Augustus/BRAKER/assets/73869977/4db91357-7593-4e6e-b1b2-fd5e2a6e8e15)

relatively closed species result
![image](https://github.com/Gaius-Augustus/BRAKER/assets/73869977/bfa7e749-d84b-42c1-be7c-5b56c5c08c7d)

Therefore, I tried _**$seqkit rmdum**_ to remove duplicated sequences. And no significant decrease in duplicated BUSCO was found.

Is there any way to remove those duplicates?

Thank you again for your cooperation.
Paul.

**Comment by tomasbruna** [comment]
This could be caused by the presence of alternative isoforms in the prediction set. Did you try selecting one representative protein per gene before running BUSCO?

**Comment by paul-bio** [comment]
Hi @tomasbruna .

No, I didn't select the representative prots. I just created a protein database from 5 closely relative species using _**cat**_.

So, according to your suggestion, do I need to remove duplications on the protein db first? And rerun Braker3?

Thank you again.

**Comment by tomasbruna** [comment]
No need, creating the database in this way is correct (proteins from many species on input are actually desirable).

What I was suggesting was to remove alternative predictions from the output protein set before running BUSCO. BRAKER3 can predict multiple [alternative isoforms](https://en.wikipedia.org/wiki/Alternative_splicing) per gene. These isoforms can be highly similar to each other (differing in only a splice site), so to BUSCO, they look like duplicates.

You can chose the longest isoform per gene with https://github.com/Gaius-Augustus/TSEBRA/blob/main/bin/get_longest_isoform.py from the braker.gtf. Then, translate the result to proteins and run BUSCO.

**Comment by paul-bio** [comment]
I tried using your Python scripts. But this error massage showed up.

> Traceback (most recent call last):
>   File "/works/creo9447/software/TSEBRA/TSEBRA-1.1.2.2/bin/get_longest_isoform.py", line 107, in <module>
>     main()
>   File "/works/creo9447/software/TSEBRA/TSEBRA-1.1.2.2/bin/get_longest_isoform.py", line 64, in main
>     n in comp], key=lambda t:t.get_cds_len())[-1]
>   File "/works/creo9447/software/TSEBRA/TSEBRA-1.1.2.2/bin/get_longest_isoform.py", line 64, in <lambda>
>     n in comp], key=lambda t:t.get_cds_len())[-1]
> AttributeError: 'Transcript' object has no attribute 'get_cds_len'

**Comment by paul-bio** [comment]
In the meantime, I used agat to remove duplicated isoformers.
And 23% of duplicated BUSCO value was decreased to 8.9%.

**Comment by tomasbruna** [comment]
Not sure what the problem is, maybe some dependencies are missing. Try this one https://github.com/gatech-genemark/ProtHint/blob/master/bin/print_longest_isoform.py, it should work on its own.

In general, any approach that selects one isoform per gene should be fine. So feel free to keep using agat if it does that.

**Comment by YingChen94** [comment]
I am getting the same error from the script `get_longest_isoform.py` in braker container. 

> I tried using your Python scripts. But this error massage showed up.
> 
> > Traceback (most recent call last):
> > File "/works/creo9447/software/TSEBRA/TSEBRA-1.1.2.2/bin/get_longest_isoform.py", line 107, in 
> > main()
> > File "/works/creo9447/software/TSEBRA/TSEBRA-1.1.2.2/bin/get_longest_isoform.py", line 64, in main
> > n in comp], key=lambda t:t.get_cds_len())[-1]
> > File "/works/creo9447/software/TSEBRA/TSEBRA-1.1.2.2/bin/get_longest_isoform.py", line 64, in 
> > n in comp], key=lambda t:t.get_cds_len())[-1]
> > AttributeError: 'Transcript' object has no attribute 'get_cds_len'
> 
> And this is the code I used **$python3 get_longest_isoform.py -g braker.gtf -o braker-filtered.gtf**

**Comment by paul-bio** [comment]
Dear @YingChen94

I solved duplication issue using agat program.

**Comment by YingChen94** [comment]
Ok I will try agat. Thank you!
